# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Process Lab
tagline:          'A Content Creation and Review System'
description:      'The Process Lab (v0.5) is a content creation system with features that allow for collaborative (formative) and summative feedback (reviews of content).'
url:              http://openworksgrp.com
baseurl:          /process-lab

author:
  name:           'OpenWorks Group'
  url:            https://twitter.com/openworksgrp

paginate:         5

# Custom vars
version:          0.5

github:
  repo:           https://github.com/OpenWorksGroup
