# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Process Lab
tagline:          'A Content Creation and Review System'
description:      'The Process Lab is a content creation system with features that allow for collaborative and summative feedback.'
url:              http://process-lab.openworksgrp.com
baseurl:          /

author:
  name:           'OpenWorks Group'
  url:            https://twitter.com/openworksgrp


# Custom vars
version:          0.5

github:
  repo:           https://github.com/OpenWorksGroup
